### ISSUE TITLE
TT 1.0.0 Tools and Equipment Hacks

### ISSUE THREAD

**Issue by Rebecca-123** [Rebecca-123/fastpage-CSA#2]
[Personal Fastpage](https://rebecca-123.github.io/fastpage-CSA/)
[New Post](https://rebecca-123.github.io/fastpage-CSA/markdown/2022/07/28/tools.html)

Part 1 - Fastpages

- [X] Build personal Fastpages / GitHub pages “_post” share the following.
- [X] Share link to personal Fastpages / GitHub pages running on github.io. 
- [X] My suggestion is to change index.html to show it is really yours.
- [X] Share link to a new page (_posts) in your Fastpages project show use of Markdown and/or HTML fragments. You will need to learn special date requirements of a file as well as a little Markdown or HTML.
- [X] Share link to Python Jupyter notebook (_notebooks) showing usage of Python: print (“Hello”)
- [X] Share link to Java Jupyter notebook (_notebooks) showing usage of Java: System.out.println(“Hello”)
- [X] Capture image/screen capture of Fastpages project showing use of an Integrated Development Environment (VS Studio)
- [X] Share link showing your GitHub insights. This is your personal activity of commit history.

Part 2 - Java Project 

- [X] Screen Capture Java project running on personal laptop localhost:0.0.0.0:8080
- [X] Share link of GitHub code commit Java on project

**Comment by jm1021** [comment]
Nice detail in Review Ticket. The only thing I would suggest is make your index.html a little more personal by next time.
